{
 "title": "Weber Smokey Mountain Temperature Dashboard",
 "time": { "from": "2025-08-04T22:37:02.080Z", "to": "2025-08-04T22:59:03.677Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "air_probe",
    "label": "Air Probe",
    "query": {
     "query": "label_values(probe_temperature_fahrenheit{probe_num!~\"$meat_probe\"},probe_num)"
    }
   },
   { "name": "air_target", "label": "Target Air Temp", "query": "225" },
   {
    "name": "meat_probe",
    "label": "Meat Probe",
    "query": {
     "query": "label_values(probe_temperature_fahrenheit,probe_num)"
    }
   },
   { "name": "meat_target", "label": "Target Meat Temp", "query": "150" },
   {
    "name": "predict_probe",
    "query": {
     "query": "label_values(probe_temperature_celsius,probe_num)"
    }
   },
   {
    "name": "predict_time",
    "query": "1m : 60,2m : 120,5m : 300,10m : 600,15m : 900,20m : 1200,25m : 1500,30m : 1800,45m : 2700,60m : 3600"
   },
   {
    "name": "predict_temp",
    "query": {
     "query": "label_values(probe_prediction_time_to_temp_timestamp,target_temp)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Current Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Meat Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_temperature_fahrenheit{probe_num=~\"$meat_probe\"}",
     "legendFormat": "Probe {{probe_num}}"
    },
    { "expr": "$meat_target", "legendFormat": "Target" }
   ]
  },
  {
   "title": "Air Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_temperature_fahrenheit{probe_num=~\"$air_probe\"}",
     "legendFormat": "Probe {{probe_num}}"
    }
   ]
  },
  {
   "title": "Meat Temp over Time (F)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "probe_temperature_fahrenheit{probe_num=~\"$meat_probe\"}",
     "legendFormat": "Probe {{probe_num}}"
    },
    { "expr": "$meat_target", "legendFormat": "Target" }
   ]
  },
  {
   "title": "Air Temp over Time (F)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "probe_temperature_fahrenheit{probe_num=~\"$air_probe\"}",
     "legendFormat": "Probe {{probe_num}}"
    },
    { "expr": "$air_target", "legendFormat": "Target" }
   ]
  },
  { "title": "Temperature Predictions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Probe Selection",
   "type": "volkovlabs-variable-panel",
   "description": "Meat Probes only",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Temperature Selection",
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Prediction Time Estimate",
   "type": "stat",
   "description": "If a probe is not shown, it means there is no valid future prediction ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((probe_prediction_time_to_temp_timestamp{target_temp=~\"$predict_temp\", probe_num=~\"$predict_probe\"}) - time()) > 0\n",
     "legendFormat": "Probe {{probe_num}} to {{target_temp}} F"
    }
   ]
  },
  {
   "title": "Estimated Time to Temperature",
   "type": "stat",
   "description": "Probe not shown if no valid prediction available",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_prediction_time_to_temp_timestamp{target_temp=~\"$predict_temp\", probe_num=~\"$predict_probe\"}*1000 >0",
     "legendFormat": "Probe {{probe_num}} @ {{target_temp}} F"
    }
   ]
  },
  {
   "title": "Time Selection",
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Predicted Temperature in ${predict_time}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "predict_linear(probe_temperature_fahrenheit{probe_num=~\"$predict_probe\"}[1m], $predict_time) >0",
     "legendFormat": "Probe {{probe_num}}"
    }
   ]
  },
  { "title": "Probe Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Probe Readings",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "probe_temperature_fahrenheit", "legendFormat": "Probe {{probe_num}}" }
   ]
  },
  {
   "title": "Probe Readings",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "probe_temperature_fahrenheit{probe_num=~\"$air_probe\"}",
     "legendFormat": "Air Probe {{probe_num}}"
    },
    {
     "expr": "probe_temperature_fahrenheit{probe_num=~\"$meat_probe\"}",
     "legendFormat": "Meat Probe {{probe_num}}"
    }
   ]
  }
 ]
}